version: "3.8"

services:


      
# Frontend
  yolo-client:
    image: navida/yolo_client:v1.0.0
    build: ./client
    container_name: yolo_client
    ports:
      - "3000:3000"
    depends_on: 
      - yolo-backend
    networks:
      - yolo-net

# Backend 
  yolo-backend:
    image: navida/yolo_backend:v1.0.0
    build: ./backend
    container_name: yolo_backend
    ports:
      - "5000:5000"
    depends_on: 
      - yolo-mongo
    networks:
      - yolo-net

# Creates the database microservice
  yolo-mongo:
    image: mongo
    container_name: yolo_mongo
    ports:
      - "27017:27017"
    networks:
      - yolo-net
    volumes:
      - type: volume
        source: yolo_data
        target: /data/db

networks:
  yolo-net:
    name: yolo_net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 10.20.0.0/16 
          ip_range: 10.20.0.0/16 

#Creates a Docker volume that persists all the data stored in the database
volumes:
  yolo_data:
    driver: local