apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
spec:
  selector:
    matchLabels:
      app: yolo-client
  replicas: 3
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: yolo-client
        image: navida/yolo_client:v1.0.0
        ports: 
        - containerPort: 3000