---
# tasks file for frontend
- name: pull frontend image
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: start frontend container
  docker_container:
    name: yolo-client
    image: "{{ frontend_image }}"
    state: started
    tty: true
    ports:
      - "3000:3000"
    restart: true
    networks:
      - name: yolo-net
