---
# tasks file for frontend
- name: pull frontend image
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: start frontend container
  docker_container:
    name: yolo-client
    image: "{{ frontend_image }}"
    state: started